var OreObject = "rocks":[{"Ore":"Veldspar","Volume":0.1},
                         {"Ore":"Scordite","Volume":0.15},
                         {"Ore":"Plagioclase","Volume":0.35},
                         {"Ore":"Pyroxeres","Volume":0.3},
                         {"Ore":"Omber","Volume":0.6},
                         {"Ore":"Kernite","Volume":1.2},
                         {"Ore":"Jaspet","Volume":2.0},
                         {"Ore":"Hemorphite","Volume":3.0},
                         {"Ore":"Hedbergite","Volume":3.0},
                         {"Ore":"Gneiss","Volume":5.0},
                         {"Ore":"Dark Ochre","Volume":8.0},
                         {"Ore":"Crokite","Volume":16.0},
                         {"Ore":"Bistot","Volume":16.0},
                         {"Ore":"Arkonor","Volume":16.0},
                         {"Ore":"Spudomain","Volume":16.0},
                         {"Ore":"Mercoxit","Volume":40.0}];                       